export const DUMMY_MOVIES = [
    {
        adult: false,
        backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
        genre_ids: [28, 12, 16, 35, 10751],
        id: 1011985,
        original_language: "en",
        original_title: "Kung Fu Panda 4",
        overview:
            "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
        popularity: 4026.558,
        poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        release_date: "2024-03-02",
        title: "Kung Fu Panda 4",
        video: false,
        vote_average: 6.994,
        vote_count: 352,
    },
    {
        adult: false,
        backdrop_path: "/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg",
        genre_ids: [28, 12, 16, 35, 10751],
        id: 1011985,
        original_language: "en",
        original_title: "Kung Fu Panda 4",
        overview:
            "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
        popularity: 4026.558,
        poster_path: "/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg",
        release_date: "2024-03-02",
        title: "Kung Fu Panda 4",
        video: false,
        vote_average: 6.994,
        vote_count: 352,
    },
];

export const DUMMY_MOVIE_CREDITS = {
    id: 1123,
    cast: [
        {
            adult: false,
            gender: 2,
            id: 504,
            known_for_department: "Acting",
            name: "Tim Robbins",
            original_name: "Tim Robbins",
            popularity: 44.403,
            profile_path: "/A4fHNLX73EQs78f2G6ObfKZnvp4.jpg",
            cast_id: 14,
            character: "Nic Vos",
            credit_id: "52fe42e8c3a36847f802be8b",
            order: 0,
        },
    ],
    crew: [
        {
            adult: false,
            gender: 2,
            id: 2226,
            known_for_department: "Directing",
            name: "Sydney Pollack",
            original_name: "Sydney Pollack",
            popularity: 24.009,
            profile_path: "/j3iXrQDiceGrAzEF6HE49zA7Wwj.jpg",
            credit_id: "52fe42e8c3a36847f802be69",
            department: "Production",
            job: "Executive Producer",
        },
    ],
};

export const DUMMY_MOVIE_DETAILS = {
    adult: false,
    backdrop_path: "/to5uhJxIin8Pi9WmREFLSUuS33L.jpg",
    belongs_to_collection: null,
    budget: 14000000,
    genres: [
        {
            id: 28,
            name: "Action",
        },
    ],
    homepage: "",
    id: 1123,
    imdb_id: "tt0437232",
    original_language: "en",
    original_title: "Catch a Fire",
    overview:
        "The true story of anti-apartheid activists in South Africa, and particularly the life of Patrick Chamusso, a timid foreman at Secunda CTL, the largest synthetic fuel plant in the world. Patrick is wrongly accused, imprisoned and tortured for an attempt to bomb the plant, with the injustice transforming the apolitical worker into a radicalised insurgent, who then carries out his own successful sabotage mission.",
    popularity: 14.558,
    poster_path: "/2sgujWX2yWH7REnDI35ZZXsqPiV.jpg",
    production_companies: [
        {
            id: 10163,
            logo_path: "/16KWBMmfPX0aJzDExDrPxSLj0Pg.png",
            name: "Working Title Films",
            origin_country: "GB",
        },
    ],
    production_countries: [
        {
            iso_3166_1: "FR",
            name: "France",
        },
    ],
    release_date: "2006-10-27",
    revenue: 5700000,
    runtime: 101,
    spoken_languages: [
        {
            english_name: "Afrikaans",
            iso_639_1: "af",
            name: "Afrikaans",
        },
    ],
    status: "Released",
    tagline: "The spark that ignites us, unites us.",
    title: "Catch a Fire",
    video: false,
    vote_average: 6.2,
    vote_count: 114,
};

export const DUMMY_SIMILAR_MOVIES = {
    results: [
        {
            adult: false,
            backdrop_path: "/v1QEIuBM1vvpvfqalahhIyXY0Cm.jpg",
            genre_ids: [12, 53, 28],
            id: 551,
            original_language: "en",
            original_title: "The Poseidon Adventure",
            overview:
                "When their ocean liner capsizes, a group of passengers struggle to survive and escape.",
            popularity: 28.545,
            poster_path: "/lIGloOrUtGDx6E4vUTGae9C1phJ.jpg",
            release_date: "1972-12-13",
            title: "The Poseidon Adventure",
            video: false,
            vote_average: 7.098,
            vote_count: 829,
        },
        {
            adult: false,
            backdrop_path: "/oIwfoUFfWfESn0Y8u8jv9lc8li1.jpg",
            genre_ids: [28, 53],
            id: 562,
            original_language: "en",
            original_title: "Die Hard",
            overview:
                "NYPD cop John McClane's plan to reconcile with his estranged wife is thrown for a serious loop when, minutes after he arrives at her office, the entire building is overtaken by a group of terrorists. With little help from the LAPD, wisecracking McClane sets out to single-handedly rescue the hostages and bring the bad guys down.",
            popularity: 41.646,
            poster_path: "/yFihWxQcmqcaBR31QM6Y8gT6aYV.jpg",
            release_date: "1988-07-15",
            title: "Die Hard",
            video: false,
            vote_average: 7.784,
            vote_count: 10658,
        },
    ],
};

export const DUMMY_PERSON_DETAILS = {
    adult: false,
    also_known_as: ["Vito Chiari", "Vito Annicchiarico"],
    biography: "",
    birthday: "1934-02-26",
    deathday: "2022-08-05",
    gender: 2,
    homepage: null,
    id: 4423,
    imdb_id: "nm0030383",
    known_for_department: "Acting",
    name: "Vito Annichiarico",
    place_of_birth: "Grottaglie, Italy",
    popularity: 0.6,
    profile_path: null,
};

export const DUMMY_PERSON_MOVIES = {
    cast: [
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [99, 53],
            id: 685905,
            original_language: "en",
            original_title: "Music and Sound Design of 'The Sixth Sense'",
            overview:
                "This making-of piece features Shaymalan and composer James Newton Howard sharing their insights into the film's powerful score and unique sound effects.",
            popularity: 1.021,
            poster_path: "/7vBgyQLxFZuC5GBrtAQfszRijSa.jpg",
            release_date: "2000-03-28",
            title: "Music and Sound Design of 'The Sixth Sense'",
            video: true,
            vote_average: 5,
            vote_count: 1,
            character: "Self",
            credit_id: "5e794e04d18b24001382b9f8",
            order: 0,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [99, 18, 28, 9648],
            id: 685686,
            original_language: "en",
            original_title: "The Making of 'Unbreakable'",
            overview:
                "This making-of piece showcases the evolution of the film from script (the entire movie is generally the first act of your typical film), the differences in crew between Unbreakable and The Sixth Sense, the thematic elements seen throughout the movie, the pace and shooting of the movie, and so on.",
            popularity: 2.503,
            poster_path: "/9d08WSkGtGz0CSRRIOa47J97ORr.jpg",
            release_date: "2001-06-19",
            title: "The Making of 'Unbreakable'",
            video: true,
            vote_average: 6.5,
            vote_count: 11,
            character: "Self",
            credit_id: "5e783d91a055ef00182f2e5f",
            order: 1,
        },
    ],
};

export const DUMMY_CAST = [
    {
        adult: false,
        gender: 2,
        id: 12898,
        known_for_department: "Acting",
        name: "Tim Allen",
        original_name: "Tim Allen",
        popularity: 2.744,
        profile_path: "/woWhZzFILVhYMAvsPL171HjMY0y.jpg",
        cast_id: 1,
        character: "Joe Scheffer",
        credit_id: "52fe44db9251416c7504353b",
        order: 0,
    },
    {
        adult: false,
        gender: 1,
        id: 31171,
        known_for_department: "Acting",
        name: "Julie Bowen",
        original_name: "Julie Bowen",
        popularity: 2.744,
        profile_path: "/fPEajDhMgM14105LxYkpEdQZlBt.jpg",
        cast_id: 2,
        character: "Meg Harper",
        credit_id: "52fe44db9251416c7504353f",
        order: 1,
    },
];
