export const DUMMY_PERSON_DETAILS = {
    adult: false,
    also_known_as: ["Vito Chiari", "Vito Annicchiarico"],
    biography: "",
    birthday: "1934-02-26",
    deathday: "2022-08-05",
    gender: 2,
    homepage: null,
    id: 4423,
    imdb_id: "nm0030383",
    known_for_department: "Acting",
    name: "Vito Annichiarico",
    place_of_birth: "Grottaglie, Italy",
    popularity: 0.6,
    profile_path: null,
};

export const DUMMY_PERSON_MOVIES = {
    cast: [
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [99, 53],
            id: 685905,
            original_language: "en",
            original_title: "Music and Sound Design of 'The Sixth Sense'",
            overview:
                "This making-of piece features Shaymalan and composer James Newton Howard sharing their insights into the film's powerful score and unique sound effects.",
            popularity: 1.021,
            poster_path: "/7vBgyQLxFZuC5GBrtAQfszRijSa.jpg",
            release_date: "2000-03-28",
            title: "Music and Sound Design of 'The Sixth Sense'",
            video: true,
            vote_average: 5,
            vote_count: 1,
            character: "Self",
            credit_id: "5e794e04d18b24001382b9f8",
            order: 0,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [99, 18, 28, 9648],
            id: 685686,
            original_language: "en",
            original_title: "The Making of 'Unbreakable'",
            overview:
                "This making-of piece showcases the evolution of the film from script (the entire movie is generally the first act of your typical film), the differences in crew between Unbreakable and The Sixth Sense, the thematic elements seen throughout the movie, the pace and shooting of the movie, and so on.",
            popularity: 2.503,
            poster_path: "/9d08WSkGtGz0CSRRIOa47J97ORr.jpg",
            release_date: "2001-06-19",
            title: "The Making of 'Unbreakable'",
            video: true,
            vote_average: 6.5,
            vote_count: 11,
            character: "Self",
            credit_id: "5e783d91a055ef00182f2e5f",
            order: 1,
        },
    ],
};
