export const DUMMY_CAST = [
    {
        adult: false,
        gender: 0,
        id: 125821,
        known_for_department: "Acting",
        name: "George Seldes",
        original_name: "George Seldes",
        popularity: 0.6,
        profile_path: "somePath",
        cast_id: 4,
        character: "Himself",
        credit_id: "52fe45bdc3a36847f80d7b35",
        order: 0,
    },
    {
        adult: false,
        gender: 0,
        id: 125821,
        known_for_department: "Acting",
        name: "George Seldes",
        original_name: "George Seldes",
        popularity: 0.6,
        profile_path: "somePath",
        cast_id: 4,
        character: "Himself",
        credit_id: "52fe45bdc3a36847f80d7b35",
        order: 0,
    },
];
